GET http://localhost:3000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTA1MDgzNTAsImV4cCI6MTcxMDUwODM2NSwiYXVkIjoiNjVmM2ZmMDk5NmI4MDY4ZGY2YjM0NzY4IiwiaXNzIjoiaHR0cHM6Ly9vYXNpcy1sb3ZhdC52ZXJjZWwuYXBwLyJ9.L2wj-PmNRAZbBp0DL5BUodbZDVS29ItDc8Fkrkh6DAs

###
GET http://localhost:3000/123_abc

###
POST  http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname":"kiki",
    "lastname":"yechuni",
    "email":"endetnsh@gmail.com",
    "password":"br0yeLule"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"endetnsh@gmail.com",
    "password":"br0yeLule"
}

###
POST http://localhost:3000/auth/refresh-token

###
DELETE  http://localhost:3000/auth/logout